{% include 'mymedia/imagefile/vue/api.js' %}
{% include 'mymedia/imagefile/vue/text.js' %}
{% include 'mymedia/imagefile/vue/tags.js' %}
{% include 'mymedia/imagefile/vue/toggle.js' %}
{% include 'mymedia/imagefile/vue/mediafile.js' %}
{% include 'mymedia/imagefile/vue/dropload.js' %}
{% include 'mymedia/imagefile/vue/gallery.js' %}
{% include 'mymedia/imagefile/vue/album.js' %}
{% include 'mymedia/imagefile/vue/image.js' %}
